### PR TITLE
Community examples through EXAMPLES.md

### PR DESCRIPTION
**Pull request by ilievskizoran**
As I suggested in #13, with further suggestion from @levibuzolic, created EXAMPLES.md where people can contribute all the creative ways they have used the API.

Started off first example of how to query the API inside of Google Sheets.

Open to suggestions on the format used in EXAMPLES.md.

⚡️

### CODE REVIEW

**Comment by ryandanger** [comment]
Apologies, not too sure how to merge this with my PR that I've done on top of yours. #24

**Comment by d11wtq** [comment]
Thanks for submitting this @ilievskizoran (and for the additions @ryandanger). There's some discussion internally as to how best to incorporate this in a way that does not create the impression that Up is officially endorsing these projects (we can't). I think what we'll do is create a separate branch and base this PR off of that, so we can add any legal disclaimers etc before we merge to master.

@ryandanger would you mind submitting your changes to @ilievskizoran's repository and working through any fixes there? Looks like a minor issue with errant escaping.

image

**Comment by d11wtq** [comment]
I also think we should not include projects without the express permission of the original author, so this PR right now is ok, but the other one includes projects where the author likely has no idea we're including them here. If they wish to be included, they can submit a PR on top of this one, or we can seek express permission. They may, for example, wish to have the freedom to simply delete or make private those projects.

**Comment by d11wtq** [comment]
Have updated the base branch. Let me know when you're happy to have this merged, taking into account my comment above. We'll add some legal disclaimer before we commit to master ❤️

**Comment by ilievskizoran** [comment]
Thank you @d11wtq for the details that all makes sense and is completely understandable on my end.
Let me know if you need anything else from me. Will sort out other PR with @ryandanger and let you know when it is updated here.

@ryandanger I'm happy to take a PR into my repo and merge it up there, providing we have explicit permission from the other authors. In the interest of time I can merge it up right away if we only include mine and your example for now 👍

**Comment by d11wtq** [comment]
> In the interest of time I can merge it up right away if we only include mine and your example for now

Seems prudent ;)

**Comment by ryandanger** [comment]
Sounds good to me. I've sent contact to the other people who I could find via [Twitter] (https://twitter.com/splatoonAU/status/1290078250434142208), however happy to have my repo added in with this original PR! ☺

**Comment by ilievskizoran** [comment]
https://github.com/ilievskizoran/api/tree/examples
@ryandanger If you wanted to make a PR into this branch on my fork with only our examples I can merge that up ASAP and get it reflected here.

**Comment by ryandanger** [comment]
Apologies, I've created #26. I attempted to make a PR but Github wasn't playing nice.

**Pull request merged**
